context.objects = [
    {   factory = adapter
        args = {
            factory.name     = api.alsa.pcm.sink
            node.name        = "MacBook_Speaker"
            node.description = "MacBook Speaker"
            media.class      = "Audio/Sink"
            api.alsa.path    = "hw:1,2"
            audio.format     = "S16LE"
            audio.rate       = 48000
            audio.channels   = 4
        }
    }
]
