PACKAGE_NAME="macbook81-audio-driver"
PACKAGE_VERSION="0.1"
PRE_BUILD="install.sh -k $kernelver"
MAKE="make"
BUILT_MODULE_NAME[0]="snd-hda-codec-cs420x"
BUILT_MODULE_LOCATION[0]="build/hda/codecs/cirrus"
DEST_MODULE_LOCATION[0]="/kernel/extra"
AUTOINSTALL="yes"
